### ISSUE TITLE
Launch tracking

### ISSUE THREAD

**Issue by kytrinyx** [exercism/arm64-assembly#1]
Edit this issue to keep track of the tasks you're working on towards launch.

We have a rough guide for how to launch a track, which is sorely outdated but
quite possibly better than nothing (I'm so sorry, I'm waaaay behind on getting
documentation updated).
https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md

Check out https://github.com/orgs/exercism/teams/track-maintainers/discussions/1
for details about the #maintainers channel in the exercism-team Slack workspace.

Please ask if you have any questions or if anything is confusing!

**Comment by bergjohan** [comment]
@kytrinyx I don't seem to have push access to this repo, would you give me permissions? Also, could you enable Travis?

**Comment by bergjohan** [comment]
@iHiD Are you able to help with the above? :)

**Comment by iHiD** [comment]
Done :)

**Comment by bergjohan** [comment]
Wow, that was quick! Thank you! :)

**Comment by bergjohan** [comment]
@iHiD This repo doesn't seem to be enabled on Travis, could you enable it?

**Comment by iHiD** [comment]
Done.

**Comment by bergjohan** [comment]
Thank you! :)
