### ISSUE TITLE
Add language blurb

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/arm64-assembly#28]
The track's `config.json` file must have a non-empty `blurb` property. This property should contain a short description (less than or equal to 400 characters) of the language. See https://github.com/exercism/docs/blob/main/building/tracks/config-json.md.

## Tracking

https://github.com/exercism/v3-launch/issues/37

**Comment by Chlorophytus** [comment]
I'll put this as a blurb once I get on my other computer. I hope this will be acceptable as a first PR.

>>> ARM64/AArch64 assembly is a low-level programming language typically used in recent smartphone and tablet bootloaders, and operating system kernels.

**Comment by ErikSchierboom** [comment]
Yep, that would be great! Thanks. I'll assign you to the issue.
